// .env의 VITE_SUPABASE_URL, VITE_SUPABASE_PUBLISHABLE_KEY를 브라우저에서 읽습니다.
window.GACHIVE_ENV = {
  VITE_SUPABASE_URL: 'https://uonjxlsxzfyggvbzemqe.supabase.co',
  VITE_SUPABASE_PUBLISHABLE_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvbmp4bHN4emZ5Z2d2YnplbXFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg4MzY0NzUsImV4cCI6MjEwNDQxMjQ3NX0.hae8Tf80EosaYyrAWU5OrMf_KmAXAkC41hP-oKvaExI'
};
